[book]
title = "Loxone MCP Rust Server Documentation"
authors = ["Ralf Anton Beier"]
description = "High-performance Model Context Protocol server for Loxone home automation systems"
language = "en"
multilingual = false
src = "docs"

[build]
build-dir = "../docs-site"
create-missing = true

[preprocessor.index]

[preprocessor.links]

[output.html]
theme = "rust"
default-theme = "rust"
preferred-dark-theme = "ayu"
curly-quotes = true
mathjax-support = false
copy-fonts = true
google-analytics = "G-XXXXXXXXXX"
additional-css = ["custom.css"]
additional-js = ["custom.js"]
git-repository-url = "https://github.com/your-repo/loxone-mcp-rust"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/your-repo/loxone-mcp-rust/edit/main/{path}"
site-url = "https://your-domain.github.io/loxone-mcp-rust/"
cname = "loxone-mcp.your-domain.com"
input-404 = "404.md"

[output.html.print]
enable = true

[output.html.fold]
enable = true
level = 0

[output.html.playground]
editable = true
copyable = true
copy-js = true
line-numbers = true
runnable = true

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3
copy-js = true