# WASM-specific Cargo configuration for WASIP2 component build
# This configuration is used when building for WASM component model

[package]
name = "loxone-mcp-wasm"
version = "0.1.0"
edition = "2021"
authors = ["Ralf Anton Beier"]
license = "MIT"
description = "Loxone Generation 1 MCP Server WASM component with Infisical integration"
repository = "https://github.com/rbeier/mcp-loxone-gen1"
keywords = ["loxone", "mcp", "home-automation", "wasm", "wasi"]
categories = ["api-bindings", "web-programming", "wasm"]

[lib]
crate-type = ["cdylib"]

[dependencies]
# Core async runtime for WASM
tokio = { version = "1.0", features = ["rt", "sync", "time"], default-features = false }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# HTTP client for WASM
reqwest = { version = "0.11", features = ["json"], default-features = false }

# Logging for WASM
tracing = "0.1"

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# URL parsing
url = { version = "2.4", features = ["serde"] }

# Base64 encoding
base64 = "0.21"

# Futures utilities
futures = "0.3"

# Time handling
chrono = { version = "0.4", features = ["serde", "wasm-bindgen"], default-features = false }

# WASM-specific dependencies
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"

# Web APIs for WASM
web-sys = { version = "0.3", features = [
  "console",
  "Window",
  "Document", 
  "Storage",
  "Request",
  "RequestInit",
  "RequestMode",
  "Response",
  "Headers",
  "AbortController",
  "AbortSignal",
  "EventSource",
  "MessageEvent",
  "Navigator",
  "Performance",
  "PerformanceTiming",
] }

# WASI interfaces
wit-bindgen = "0.16"

# Component model support
cargo-component-bindings = "0.1"

[features]
default = ["infisical", "wasi-keyvalue"]

# Enable Infisical integration
infisical = []

# Enable WASI keyvalue store
wasi-keyvalue = []

# Enable additional logging for debugging
debug-logging = []

[profile.release]
# Optimize for size in WASM
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

# Optimize all dependencies for size
[profile.release.package."*"]
opt-level = "z"

[dev-dependencies]
wasm-bindgen-test = "0.3"
console_error_panic_hook = "0.1"

[package.metadata.component]
package = "loxone:mcp"

[package.metadata.component.dependencies]
"wasi:http" = { path = "wit/deps/http" }
"wasi:keyvalue" = { path = "wit/deps/keyvalue" }
"wasi:config" = { path = "wit/deps/config" }
"wasi:cli" = { path = "wit/deps/cli" }
"wasi:logging" = { path = "wit/deps/logging" }

[package.metadata.component.target]
path = "wit"

# Custom build script for component generation
[[bin]]
name = "generate-component"
path = "src/bin/generate_component.rs"
required-features = ["wasi-keyvalue"]